export type TerminalCommandResult = {
  lines: string[];
};

export type TerminalCommands = Record<string, TerminalCommandResult>;

export const AVAILABLE_COMMANDS = [
  "contacts",
  "education",
  "exit",
  "experience",
  "help",
  "life",
  "projects",
  "skills",
  "system --init",
  "whoami",
] as const;

export const TERMINAL_COMMANDS: TerminalCommands = {
  "system --init": {
    lines: [
      "System initialized...",
      "",
      "Welcome to the Dev/Ops Environment.",
      "",
      "User: DevOps Architect",
      "Status: Online",
      "Kernel: v5.15.0-generic",
      "",
      "Available commands:",
      "  → contacts",
      "  → education",
      "  → experience",
      "  → life",
      "  → projects",
      "  → skills",
      "  → whoami",
      "",
      "Tip:",
      "  - Type 'help' to list commands.",
      "  - Type 'clear' to clear the screen.",
      "  - Type 'exit' to exit the terminal.",
    ],
  },
  whoami: {
    lines: [
      "Hello, I'm Alexandro Georgiev. I'm a software engineer passionate about automation, system reliability, and cross-functional problem-solving.",
      " ",
      "With a foundation in backend scripting and a strong grasp of DevOps culture and tools, I specialize in: Python Automation | DevOps Engineer | Fullstack Developer (React & Next.js).",
      " ",
      "★ Python Automation & DevOps",
      "  • Designed and deployed scalable CI/CD pipelines using Jenkins, Docker, Groovy, and Git",
      "  • Automated OS provisioning and upgrades across hundreds of servers with Python/Bash, Redfish API, and Airflow",
      "  • Implemented logging, backup, and monitoring solutions that improved operational stability and resolution times",
      "  • Worked hands-on with Linux kernel tuning, IPMI tooling, and image building (Cubic)",
      "",
      "★ Cloud & Infrastructure",
      "  • Built infrastructure and automation on both AWS and GCP (Cloud Run, Cloud Build, IAM, S3)",
      "  • Worked with Google Cloud services and cloud automation patterns in production",
      "  • Employed Ansible and Airflow for orchestrated deployments and task scheduling",
      "",
      "★ Fullstack Development",
      "  • Built and maintained front-end and internal tools using React, Next.js, and TanStack Query",
      "  • Developed backend APIs with Node.js, Prisma, and PostgreSQL",
      "  • Created customer-facing applications and internal dashboards, optimizing UX and performance",
      "",
      "★ Team & Delivery Focus",
      "  • Comfortable in Agile teams: sprint planning, documentation, cross-departmental communication",
      "  • Known for debugging under pressure, delivering reliable infrastructure, and bridging Dev and Ops teams",
      "",
      "★ I’m especially passionate about reducing manual toil through automation and helping teams ship faster, safer, and with confidence.",
      "",
    ],
  },
  contacts: {
    lines: [
      "  - GitHub: https://github.com/ag913331",
      "  - LinkedIn: www.linkedin.com/in/alexandro-georgiev-711b631b5",
      "  - Email: georgievalexandro@gmail.com",
    ],
  },
  education: {
    lines: [
      "{",
      "     \"education\": [",
      "         {",
      "             \"institution\": \"High School of Mathematics 'Dr Petar Beron' - Varna\",",
      "             \"degree\": \"High School Diploma\",",
      "             \"field_of_study\": \"Mathematics and Internet Technologies\",",
      "             \"period\": \"2011 - 2016\"",
      "         },",
      "         {",
      "             \"institution\": \"Technical University of Varna\",",
      "             \"degree\": \"Bachelor's degree\",",
      "             \"field_of_study\": \"Software and Internet Technologies\",",
      "             \"period\": \"2016 - 2020\"",
      "         },",
      "         {",
      "             \"institution\": \"Technical University of Varna\",",
      "             \"degree\": \"Master's degree\",",
      "             \"field_of_study\": \"Computer Software Engineering\",",
      "             \"period\": \"2020 - 2022\"",
      "         }",
      "     ]",
      "}",
    ],
  },
  experience: {
    lines: [
      "Experience:",
      "",
      "|",
      "o--------> Frontend Developer",
      "|          type: Full-time",
      "|          period: Aug 2018 - Aug 2020",
      "|          company: BROKER INS ONLINE",
      "|          location: Varna, Bulgaria",
      "|          description:",
      "|            * Created dashboards and APIs for modeling and managing insurance products",
      "|            * Built customer-facing and internal tools using React and Node.js",
      "|            * Collaborated with business stakeholders to define and deliver features",
      "|            * Enhanced performance and responsiveness through testing and optimization",
      "|",
      "|",
      "o--------> Fullstack Developer",
      "|          type: Full-time",
      "|          period: Aug 2020 - Jan 2022",
      "|          company: InsInCloud",
      "|          location: Varna, Bulgaria",
      "|          description:",
      "|            * Built reusable UI components using React and Vue",
      "|            * Integrated RESTful APIs and managed global state with Redux",
      "|            * Employed Jest and Mocha for test coverage and quality assurance",
      "|            * Automated repetitive dev tasks with Python, Bash, and CI/CD pipelines",
      "|            * Collaborated in Agile teams, improving development cycles and delivery speed",
      "|",
      "|",
      "o--------> DevOps & Automation Engineer",
      "|          type: Full-time",
      "|          period: Feb 2022 - Apr 2024",
      "|          company: MB Consulting",
      "|          location: Remote",
      "|          description:",
      "|            * Automated OS transition of production servers from CentOS to Ubuntu",
      "|            * Developed unattended installation images with Cubic, Redfish API, and Bash",
      "|            * Streamlined CI/CD pipelines using Jenkins, Groovy, and Docker",
      "|            * Automated testing and recovery processes to enhance uptime and reliability",
      "|            * Built incident response tools and improved logging/monitoring systems",
      "|            * Promoted DevOps culture by bridging Dev, Ops, and QA teams",
      "|",
      "|",
      "o--------> Fullstack & Cloud DevOps Engineer",
      "|          type: Full-time",
      "|          period: Nov 2024 - Current",
      "|          company: BuildColab",
      "|          location: Varna, Bulgaria",
      "|          description:",
      "|            * Developed frontend apps using React, Next.js, and TanStack React Query",
      "|            * Built backend APIs with Node.js and Prisma, integrating PostgreSQL",
      "|            * Implemented CI/CD pipelines using Google Cloud (Cloud Run, Cloud Build, IAM)",
      "|            * Automated deployments and testing via GitHub Actions",
      "|            * Contributed to sprint planning, documentation, and DevOps processes",
    ],
  },
  skills: {
    lines: [
      "★ Programming & Problem-Solving",
      "  - Programming | Problem-Solving",
      "  - Effective Communication",
      "",
      "★ Programming Languages",
      "  - Python",
      "  - JavaScript",
      "  - Bash",
      "  - PHP",
      "",
      "★ Frontend",
      "  - React",
      "  - Next.js",
      "  - Vue",
      "  - UI Frameworks: Material-UI / Ant Design / Bootstrap",
      "  - Custom UI library development",
      "",
      "★ Backend & Data",
      "  - Node.js",
      "  - REST APIs",
      "  - Prisma ORM",
      "  - PostgreSQL",
      "  - Microservice design & development",
      "  - System & application integration",
      "",
      "★ DevOps, Cloud & CI/CD",
      "  - Continuous Integration & Continuous Delivery (CI/CD)",
      "  - GitHub Actions",
      "  - Jenkins",
      "  - Groovy scripts",
      "  - Git",
      "  - Docker | Docker Compose",
      "  - Podman | Podman Compose",
      "  - Google Cloud Platform (GCP)",
      "",
      "★ Automation, Ops & Reliability",
      "  - Linux + Bash scripting",
      "  - Linux system administration & kernel tuning",
      "  - Service maintenance and monitoring",
      "  - Service monitoring and logging",
      "  - Unattended server installation",
      "",
      "★ IaC & Orchestration",
      "  - Ansible",
      "  - Airflow",
      "",
      "★ Testing & Quality Assurance",
      "  - PyTest | PyUnit",
      "  - Jest",
      "",
      "★ Hardware / BMC & Provisioning Tooling",
      "  - Redfish API",
      "  - Supermicro IPMI | HP IPMI",
      "  - Cubic (create/modify installation images)",
      "",
      "★ Tooling",
      "  - CLI tools: Vim, Linux commands",
      "",
      "★ Delivery",
      "  - Full-stack software development",
      "  - Project management (planning, execution, risk management)",
    ],
  },
  projects: {
    lines: [
      "Featured projects:",
      "  - <Project A>: <one-liner>  (link)",
      "  - <Project B>: <one-liner>  (link)",
      "  - <Project C>: <one-liner>  (link)",
      "",
      "Tip: replace these placeholders in src/components/terminal/commands.ts",
    ],
  },
  life: {
    lines: [
      "Outside of work:",
      "  - Homelab tinkering, self-hosting, automation",
      "  - Linux customization, CLI tooling",
      "  - Learning systems design + security",
    ],
  },
  help: {
    lines: [
      "Commands:",
      ...AVAILABLE_COMMANDS.map((c) => `  - ${c}`),
      "",
      "Notes:",
      "  - Commands are case-sensitive.",
      "  - Use ↑ / ↓ to cycle history.",
      "  - Use Ctrl+L to clear.",
      "  - Use Tab to autocomplete commands.",
    ],
  },
};


